# Generated by Django 6.0 on 2026-01-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_pet_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='life',
            field=models.BooleanField(default=True),
        ),
    ]
