# Generated by Django 6.0 on 2026-01-05 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_pet_life'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='life',
            new_name='alive',
        ),
    ]
